version: '3.3'
services:

  # rstudio:
  #   image: rocker/geospatial:latest
  #   ports:
  #     - 8787:8787
  #   volumes:
  #     - .:/home/rstudio/work
  #   environment:
  #     PASSWORD: andy1234
  
  database:
    image: postgis/postgis:12-3.0-alpine
    ports:
      - 5432:5432
    volumes:
      - ./data/database:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: andy1234
      POSTGRES_USER: postgres
      PGDATA: /tmp

  jupyter-notebook:
    image: jupyter/datascience-notebook:python-3.8.6
    ports:
      - 8889:8888
    volumes:
      - .:/home/jovyan/work
    command: ["jupyter", "lab", "--NotebookApp.token=''"]
    env_file: .env

  pgadmin:
    image: dpage/pgadmin4:5.7
    depends_on:
      - database
    ports:
      - 81:80
    environment:
      PGADMIN_DEFAULT_EMAIL: aarmestobrosio@buenosaires.gob.ar
      PGADMIN_DEFAULT_PASSWORD: andy1234

# para acceder a DB desde pgadmin utilizar host database